// Базовые эффекты тренировок (кардио, силовые, водные и зимние виды)

import { WorkoutEffect } from '../types';

export type WorkoutEffectTable = Record<number, WorkoutEffect>;

// Ходьба (улица / зал)
export const WALKING_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 0,
    endurance: 2,
    flexibility: 0,
    agility: 0,
    speed: 0,
    reflex: 0,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -1,
    health: 2,
    xp: 5,
  },
  30: {
    strength: 1,
    endurance: 5,
    flexibility: 1,
    agility: 1,
    speed: 1,
    reflex: 0,
    hunger: -2,
    thirst: -2,
    sleepiness: -4,
    energy: -2,
    health: 4,
    xp: 12,
  },
  45: {
    strength: 1,
    endurance: 8,
    flexibility: 1,
    agility: 1,
    speed: 1,
    reflex: 1,
    hunger: -3,
    thirst: -3,
    sleepiness: -6,
    energy: -4,
    health: 6,
    xp: 20,
  },
  60: {
    strength: 2,
    endurance: 10,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 1,
    hunger: -4,
    thirst: -4,
    sleepiness: -8,
    energy: -6,
    health: 8,
    xp: 30,
  },
};

// Бег (улица / зал / дорожка)
export const RUNNING_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 1,
    endurance: 3,
    flexibility: 0,
    agility: 1,
    speed: 2,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -4,
    health: 1,
    xp: 15,
  },
  30: {
    strength: 2,
    endurance: 8,
    flexibility: 1,
    agility: 2,
    speed: 5,
    reflex: 2,
    hunger: -5,
    thirst: -5,
    sleepiness: -6,
    energy: -10,
    health: 3,
    xp: 40,
  },
  45: {
    strength: 3,
    endurance: 14,
    flexibility: 1,
    agility: 3,
    speed: 8,
    reflex: 3,
    hunger: -8,
    thirst: -9,
    sleepiness: -8,
    energy: -18,
    health: 4,
    xp: 70,
  },
  60: {
    strength: 3,
    endurance: 18,
    flexibility: 1,
    agility: 3,
    speed: 9,
    reflex: 3,
    hunger: -12,
    thirst: -14,
    sleepiness: -6,
    energy: -25,
    health: 3,
    xp: 90,
  },
};

// Велосипед (улица / зал)
export const CYCLING_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 1,
    endurance: 3,
    flexibility: 0,
    agility: 0,
    speed: 1,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -3,
    health: 1,
    xp: 12,
  },
  30: {
    strength: 2,
    endurance: 7,
    flexibility: 1,
    agility: 1,
    speed: 3,
    reflex: 2,
    hunger: -4,
    thirst: -4,
    sleepiness: -6,
    energy: -8,
    health: 3,
    xp: 35,
  },
  45: {
    strength: 3,
    endurance: 12,
    flexibility: 1,
    agility: 2,
    speed: 5,
    reflex: 3,
    hunger: -7,
    thirst: -7,
    sleepiness: -8,
    energy: -14,
    health: 5,
    xp: 60,
  },
  60: {
    strength: 4,
    endurance: 16,
    flexibility: 1,
    agility: 2,
    speed: 6,
    reflex: 3,
    hunger: -10,
    thirst: -11,
    sleepiness: -6,
    energy: -20,
    health: 5,
    xp: 85,
  },
};

// Эллипсоид
export const ELLIPTICAL_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 1,
    endurance: 3,
    flexibility: 1,
    agility: 1,
    speed: 1,
    reflex: 0,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -3,
    health: 1,
    xp: 12,
  },
  30: {
    strength: 2,
    endurance: 7,
    flexibility: 2,
    agility: 2,
    speed: 2,
    reflex: 1,
    hunger: -4,
    thirst: -4,
    sleepiness: -6,
    energy: -7,
    health: 3,
    xp: 35,
  },
  45: {
    strength: 3,
    endurance: 12,
    flexibility: 3,
    agility: 3,
    speed: 3,
    reflex: 2,
    hunger: -7,
    thirst: -7,
    sleepiness: -8,
    energy: -12,
    health: 5,
    xp: 60,
  },
  60: {
    strength: 3,
    endurance: 15,
    flexibility: 3,
    agility: 3,
    speed: 3,
    reflex: 2,
    hunger: -10,
    thirst: -10,
    sleepiness: -7,
    energy: -18,
    health: 6,
    xp: 85,
  },
};

// Эргометр (гребля в зале)
export const ROWING_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 1,
    speed: 1,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 1,
    xp: 15,
  },
  30: {
    strength: 5,
    endurance: 7,
    flexibility: 2,
    agility: 2,
    speed: 2,
    reflex: 2,
    hunger: -5,
    thirst: -5,
    sleepiness: -5,
    energy: -10,
    health: 3,
    xp: 45,
  },
  45: {
    strength: 8,
    endurance: 12,
    flexibility: 3,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -8,
    thirst: -9,
    sleepiness: -7,
    energy: -18,
    health: 4,
    xp: 75,
  },
  60: {
    strength: 10,
    endurance: 15,
    flexibility: 3,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -12,
    thirst: -14,
    sleepiness: -5,
    energy: -25,
    health: 3,
    xp: 100,
  },
};

// Степпер (лестница)
export const STEPPER_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 1,
    endurance: 3,
    flexibility: 0,
    agility: 1,
    speed: 1,
    reflex: 0,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 1,
    xp: 12,
  },
  30: {
    strength: 3,
    endurance: 7,
    flexibility: 1,
    agility: 2,
    speed: 2,
    reflex: 1,
    hunger: -5,
    thirst: -5,
    sleepiness: -5,
    energy: -10,
    health: 3,
    xp: 40,
  },
  45: {
    strength: 5,
    endurance: 12,
    flexibility: 2,
    agility: 3,
    speed: 3,
    reflex: 2,
    hunger: -8,
    thirst: -9,
    sleepiness: -7,
    energy: -17,
    health: 4,
    xp: 70,
  },
  60: {
    strength: 6,
    endurance: 15,
    flexibility: 2,
    agility: 3,
    speed: 3,
    reflex: 2,
    hunger: -12,
    thirst: -14,
    sleepiness: -5,
    energy: -24,
    health: 3,
    xp: 95,
  },
};

// Хайкинг (пеший туризм)
export const HIKING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 4,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 1,
    hunger: -3,
    thirst: -3,
    sleepiness: -4,
    energy: -5,
    health: 3,
    xp: 20,
  },
  60: {
    strength: 4,
    endurance: 9,
    flexibility: 2,
    agility: 4,
    speed: 2,
    reflex: 2,
    hunger: -8,
    thirst: -8,
    sleepiness: -8,
    energy: -12,
    health: 6,
    xp: 50,
  },
  90: {
    strength: 6,
    endurance: 15,
    flexibility: 3,
    agility: 6,
    speed: 3,
    reflex: 3,
    hunger: -14,
    thirst: -15,
    sleepiness: -10,
    energy: -22,
    health: 8,
    xp: 85,
  },
  120: {
    strength: 7,
    endurance: 20,
    flexibility: 3,
    agility: 7,
    speed: 3,
    reflex: 3,
    hunger: -20,
    thirst: -22,
    sleepiness: -8,
    energy: -30,
    health: 9,
    xp: 120,
  },
};

// ВИИТ / HIIT
export const HIIT_EFFECTS: WorkoutEffectTable = {
  5: {
    strength: 2,
    endurance: 2,
    flexibility: 0,
    agility: 1,
    speed: 3,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -1,
    energy: -6,
    health: 0,
    xp: 10,
  },
  10: {
    strength: 4,
    endurance: 5,
    flexibility: 1,
    agility: 2,
    speed: 6,
    reflex: 4,
    hunger: -4,
    thirst: -4,
    sleepiness: -2,
    energy: -12,
    health: -2,
    xp: 25,
  },
  15: {
    strength: 6,
    endurance: 8,
    flexibility: 1,
    agility: 3,
    speed: 9,
    reflex: 6,
    hunger: -6,
    thirst: -6,
    sleepiness: -3,
    energy: -18,
    health: -5,
    xp: 45,
  },
  20: {
    strength: 8,
    endurance: 10,
    flexibility: 1,
    agility: 4,
    speed: 12,
    reflex: 8,
    hunger: -8,
    thirst: -8,
    sleepiness: -2,
    energy: -24,
    health: -8,
    xp: 65,
  },
};

// Скакалка
export const JUMP_ROPE_EFFECTS: WorkoutEffectTable = {
  5: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 2,
    speed: 2,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 1,
    xp: 8,
  },
  10: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 4,
    speed: 4,
    reflex: 4,
    hunger: -3,
    thirst: -3,
    sleepiness: -4,
    energy: -6,
    health: 2,
    xp: 20,
  },
  15: {
    strength: 3,
    endurance: 6,
    flexibility: 3,
    agility: 6,
    speed: 6,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -6,
    energy: -9,
    health: 3,
    xp: 35,
  },
  20: {
    strength: 4,
    endurance: 8,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 7,
    hunger: -7,
    thirst: -7,
    sleepiness: -5,
    energy: -12,
    health: 3,
    xp: 50,
  },
};

// Традиционная силовая тренировка (с весами/тренажерами)
export const STRENGTH_TRAINING_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 5,
    endurance: 2,
    flexibility: 1,
    agility: 1,
    speed: 0,
    reflex: 0,
    hunger: -3,
    thirst: -2,
    sleepiness: 3,
    energy: -5,
    health: -2,
    xp: 20,
  },
  30: {
    strength: 12,
    endurance: 6,
    flexibility: 2,
    agility: 3,
    speed: 1,
    reflex: 1,
    hunger: -8,
    thirst: -5,
    sleepiness: 8,
    energy: -12,
    health: -5,
    xp: 55,
  },
  45: {
    strength: 20,
    endurance: 10,
    flexibility: 4,
    agility: 5,
    speed: 2,
    reflex: 2,
    hunger: -15,
    thirst: -10,
    sleepiness: 15,
    energy: -20,
    health: -12,
    xp: 90,
  },
  60: {
    strength: 25,
    endurance: 12,
    flexibility: 5,
    agility: 6,
    speed: 2,
    reflex: 3,
    hunger: -22,
    thirst: -15,
    sleepiness: 25,
    energy: -30,
    health: -20,
    xp: 75,
  },
  75: {
    strength: 28,
    endurance: 13,
    flexibility: 5,
    agility: 6,
    speed: 1,
    reflex: 3,
    hunger: -30,
    thirst: -20,
    sleepiness: 35,
    energy: -40,
    health: -30,
    xp: 50,
  },
};

// Функционально-силовая (собственный вес, кроссфит)
export const FUNCTIONAL_STRENGTH_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 4,
    endurance: 3,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: 2,
    energy: -4,
    health: -1,
    xp: 25,
  },
  30: {
    strength: 9,
    endurance: 7,
    flexibility: 2,
    agility: 4,
    speed: 3,
    reflex: 3,
    hunger: -5,
    thirst: -5,
    sleepiness: 6,
    energy: -10,
    health: -4,
    xp: 65,
  },
  45: {
    strength: 14,
    endurance: 12,
    flexibility: 3,
    agility: 6,
    speed: 5,
    reflex: 5,
    hunger: -9,
    thirst: -9,
    sleepiness: 10,
    energy: -18,
    health: -10,
    xp: 95,
  },
  60: {
    strength: 18,
    endurance: 16,
    flexibility: 4,
    agility: 7,
    speed: 6,
    reflex: 6,
    hunger: -13,
    thirst: -14,
    sleepiness: 14,
    energy: -26,
    health: -18,
    xp: 110,
  },
};

// Кор (мышцы кора/пресса)
export const CORE_EFFECTS: WorkoutEffectTable = {
  10: {
    strength: 2,
    endurance: 1,
    flexibility: 1,
    agility: 1,
    speed: 0,
    reflex: 0,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 0,
    xp: 10,
  },
  20: {
    strength: 4,
    endurance: 3,
    flexibility: 2,
    agility: 2,
    speed: 1,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -4,
    health: 1,
    xp: 25,
  },
  30: {
    strength: 6,
    endurance: 4,
    flexibility: 3,
    agility: 3,
    speed: 1,
    reflex: 1,
    hunger: -3,
    thirst: -3,
    sleepiness: -4,
    energy: -6,
    health: 2,
    xp: 40,
  },
};

// Пилатес
export const PILATES_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 1,
    flexibility: 3,
    agility: 2,
    speed: 0,
    reflex: 0,
    hunger: -1,
    thirst: -1,
    sleepiness: -3,
    energy: -2,
    health: 2,
    xp: 15,
  },
  40: {
    strength: 4,
    endurance: 3,
    flexibility: 6,
    agility: 4,
    speed: 1,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -5,
    energy: -4,
    health: 4,
    xp: 35,
  },
  60: {
    strength: 6,
    endurance: 4,
    flexibility: 8,
    agility: 5,
    speed: 1,
    reflex: 2,
    hunger: -3,
    thirst: -3,
    sleepiness: -7,
    energy: -6,
    health: 6,
    xp: 55,
  },
};

// Йога
export const YOGA_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 1,
    flexibility: 4,
    agility: 2,
    speed: 0,
    reflex: 1,
    hunger: 0,
    thirst: 0,
    sleepiness: -4,
    energy: -1,
    health: 3,
    xp: 15,
  },
  40: {
    strength: 2,
    endurance: 2,
    flexibility: 8,
    agility: 3,
    speed: 0,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -7,
    energy: -2,
    health: 6,
    xp: 30,
  },
  60: {
    strength: 3,
    endurance: 3,
    flexibility: 12,
    agility: 4,
    speed: 0,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -10,
    energy: -3,
    health: 8,
    xp: 45,
  },
};

// Барре (балетная тренировка)
export const BARRE_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 2,
    flexibility: 3,
    agility: 3,
    speed: 1,
    reflex: 1,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 20,
  },
  40: {
    strength: 4,
    endurance: 4,
    flexibility: 6,
    agility: 6,
    speed: 2,
    reflex: 2,
    hunger: -3,
    thirst: -3,
    sleepiness: -4,
    energy: -6,
    health: 4,
    xp: 40,
  },
  60: {
    strength: 5,
    endurance: 6,
    flexibility: 8,
    agility: 8,
    speed: 3,
    reflex: 3,
    hunger: -4,
    thirst: -4,
    sleepiness: -5,
    energy: -8,
    health: 5,
    xp: 60,
  },
};

// Растяжка (Flexibility)
export const STRETCHING_EFFECTS: WorkoutEffectTable = {
  10: {
    strength: 0,
    endurance: 0,
    flexibility: 4,
    agility: 1,
    speed: 0,
    reflex: 0,
    hunger: 0,
    thirst: 0,
    sleepiness: -3,
    energy: -1,
    health: 2,
    xp: 10,
  },
  20: {
    strength: 1,
    endurance: 1,
    flexibility: 8,
    agility: 2,
    speed: 0,
    reflex: 1,
    hunger: -1,
    thirst: -1,
    sleepiness: -5,
    energy: -2,
    health: 4,
    xp: 20,
  },
  30: {
    strength: 1,
    endurance: 1,
    flexibility: 12,
    agility: 3,
    speed: 1,
    reflex: 1,
    hunger: -1,
    thirst: -1,
    sleepiness: -7,
    energy: -3,
    health: 5,
    xp: 30,
  },
};

// Заминка (восстановление после тренировки)
export const COOLDOWN_EFFECTS: WorkoutEffectTable = {
  5: {
    strength: 0,
    endurance: 0,
    flexibility: 1,
    agility: 0,
    speed: 0,
    reflex: 0,
    hunger: 0,
    thirst: 0,
    sleepiness: -2,
    energy: 0,
    health: 1,
    xp: 5,
  },
  10: {
    strength: 0,
    endurance: 0,
    flexibility: 2,
    agility: 1,
    speed: 0,
    reflex: 0,
    hunger: 0,
    thirst: 0,
    sleepiness: -3,
    energy: 1,
    health: 2,
    xp: 10,
  },
  15: {
    strength: 0,
    endurance: 1,
    flexibility: 3,
    agility: 1,
    speed: 0,
    reflex: 0,
    hunger: 0,
    thirst: 0,
    sleepiness: -4,
    energy: 2,
    health: 3,
    xp: 15,
  },
};

// Смешанная кардио (микс бег/велотрен/эллипс)
export const MIXED_CARDIO_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 4,
    flexibility: 1,
    agility: 1,
    speed: 2,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -4,
    health: 2,
    xp: 30,
  },
  40: {
    strength: 3,
    endurance: 9,
    flexibility: 2,
    agility: 2,
    speed: 4,
    reflex: 2,
    hunger: -5,
    thirst: -5,
    sleepiness: -6,
    energy: -10,
    health: 4,
    xp: 60,
  },
  60: {
    strength: 4,
    endurance: 14,
    flexibility: 3,
    agility: 3,
    speed: 6,
    reflex: 3,
    hunger: -8,
    thirst: -9,
    sleepiness: -8,
    energy: -18,
    health: 5,
    xp: 90,
  },
};

// Плавание в бассейне (круги)
export const POOL_SWIMMING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 1,
    speed: 2,
    reflex: 1,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -4,
    health: 2,
    xp: 30,
  },
  40: {
    strength: 4,
    endurance: 8,
    flexibility: 4,
    agility: 2,
    speed: 4,
    reflex: 2,
    hunger: -4,
    thirst: -4,
    sleepiness: -6,
    energy: -9,
    health: 4,
    xp: 60,
  },
  60: {
    strength: 6,
    endurance: 12,
    flexibility: 5,
    agility: 3,
    speed: 6,
    reflex: 3,
    hunger: -7,
    thirst: -7,
    sleepiness: -8,
    energy: -15,
    health: 6,
    xp: 90,
  },
};

// Плавание в открытой воде (GPS)
export const OPEN_WATER_SWIMMING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 5,
    flexibility: 2,
    agility: 2,
    speed: 2,
    reflex: 2,
    hunger: -2,
    thirst: -3,
    sleepiness: -3,
    energy: -5,
    health: 2,
    xp: 35,
  },
  40: {
    strength: 5,
    endurance: 9,
    flexibility: 4,
    agility: 3,
    speed: 4,
    reflex: 3,
    hunger: -5,
    thirst: -6,
    sleepiness: -6,
    energy: -10,
    health: 4,
    xp: 70,
  },
  60: {
    strength: 7,
    endurance: 14,
    flexibility: 5,
    agility: 4,
    speed: 6,
    reflex: 4,
    hunger: -8,
    thirst: -10,
    sleepiness: -8,
    energy: -18,
    health: 6,
    xp: 100,
  },
};

// Водные виды спорта (общее)
export const WATER_SPORTS_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 25,
  },
  40: {
    strength: 4,
    endurance: 6,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -4,
    thirst: -4,
    sleepiness: -4,
    energy: -7,
    health: 4,
    xp: 50,
  },
  60: {
    strength: 5,
    endurance: 9,
    flexibility: 3,
    agility: 4,
    speed: 3,
    reflex: 4,
    hunger: -6,
    thirst: -7,
    sleepiness: -6,
    energy: -12,
    health: 5,
    xp: 75,
  },
};

// Аквааэробика
export const AQUA_AEROBICS_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 3,
    flexibility: 2,
    agility: 1,
    speed: 0,
    reflex: 0,
    hunger: -1,
    thirst: -1,
    sleepiness: -3,
    energy: -2,
    health: 3,
    xp: 20,
  },
  40: {
    strength: 2,
    endurance: 6,
    flexibility: 4,
    agility: 2,
    speed: 1,
    reflex: 1,
    hunger: -3,
    thirst: -3,
    sleepiness: -5,
    energy: -4,
    health: 5,
    xp: 40,
  },
  60: {
    strength: 3,
    endurance: 9,
    flexibility: 5,
    agility: 3,
    speed: 2,
    reflex: 2,
    hunger: -4,
    thirst: -4,
    sleepiness: -7,
    energy: -6,
    health: 7,
    xp: 60,
  },
};

// Сёрфинг
export const SURFING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 3,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -2,
    thirst: -3,
    sleepiness: -2,
    energy: -4,
    health: 2,
    xp: 35,
  },
  40: {
    strength: 5,
    endurance: 6,
    flexibility: 3,
    agility: 5,
    speed: 3,
    reflex: 5,
    hunger: -4,
    thirst: -6,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 70,
  },
  60: {
    strength: 7,
    endurance: 9,
    flexibility: 4,
    agility: 7,
    speed: 4,
    reflex: 7,
    hunger: -7,
    thirst: -10,
    sleepiness: -6,
    energy: -15,
    health: 5,
    xp: 100,
  },
};

// Парусный спорт
export const SAILING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 1,
    endurance: 2,
    flexibility: 0,
    agility: 1,
    speed: 0,
    reflex: 1,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 2,
    xp: 20,
  },
  60: {
    strength: 3,
    endurance: 4,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -3,
    thirst: -3,
    sleepiness: -2,
    energy: -4,
    health: 4,
    xp: 40,
  },
  90: {
    strength: 4,
    endurance: 6,
    flexibility: 1,
    agility: 3,
    speed: 1,
    reflex: 3,
    hunger: -4,
    thirst: -5,
    sleepiness: -3,
    energy: -6,
    health: 5,
    xp: 60,
  },
};

// Гребля (на улице)
export const OUTDOOR_ROWING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 3,
    flexibility: 1,
    agility: 1,
    speed: 1,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 1,
    xp: 30,
  },
  40: {
    strength: 6,
    endurance: 7,
    flexibility: 2,
    agility: 2,
    speed: 2,
    reflex: 3,
    hunger: -4,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 3,
    xp: 60,
  },
  60: {
    strength: 9,
    endurance: 11,
    flexibility: 3,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -7,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 4,
    xp: 90,
  },
};

// Паддл-спорт (байдарки/каноэ)
export const PADDLE_SPORTS_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 3,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 2,
    xp: 30,
  },
  40: {
    strength: 5,
    endurance: 6,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -4,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 60,
  },
  60: {
    strength: 7,
    endurance: 9,
    flexibility: 3,
    agility: 4,
    speed: 3,
    reflex: 4,
    hunger: -7,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 5,
    xp: 90,
  },
};

// Водное поло
export const WATER_POLO_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 4,
    flexibility: 1,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -2,
    thirst: -3,
    sleepiness: -2,
    energy: -5,
    health: 2,
    xp: 40,
  },
  40: {
    strength: 5,
    endurance: 8,
    flexibility: 2,
    agility: 5,
    speed: 4,
    reflex: 5,
    hunger: -5,
    thirst: -6,
    sleepiness: -4,
    energy: -11,
    health: 4,
    xp: 80,
  },
  60: {
    strength: 7,
    endurance: 12,
    flexibility: 3,
    agility: 7,
    speed: 6,
    reflex: 7,
    hunger: -8,
    thirst: -10,
    sleepiness: -6,
    energy: -18,
    health: 5,
    xp: 110,
  },
};

// Лыжи (беговые / спуск)
export const SKIING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 4,
    flexibility: 1,
    agility: 2,
    speed: 2,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -4,
    health: 2,
    xp: 35,
  },
  60: {
    strength: 4,
    endurance: 9,
    flexibility: 2,
    agility: 4,
    speed: 4,
    reflex: 4,
    hunger: -5,
    thirst: -5,
    sleepiness: -6,
    energy: -10,
    health: 4,
    xp: 70,
  },
  90: {
    strength: 6,
    endurance: 14,
    flexibility: 3,
    agility: 6,
    speed: 6,
    reflex: 6,
    hunger: -8,
    thirst: -9,
    sleepiness: -8,
    energy: -18,
    health: 5,
    xp: 100,
  },
};

// Сноубординг
export const SNOWBOARDING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 3,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 2,
    xp: 35,
  },
  60: {
    strength: 4,
    endurance: 6,
    flexibility: 3,
    agility: 5,
    speed: 4,
    reflex: 5,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 70,
  },
  90: {
    strength: 6,
    endurance: 9,
    flexibility: 4,
    agility: 7,
    speed: 6,
    reflex: 7,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 5,
    xp: 100,
  },
};

// Зимние виды спорта (общее)
export const WINTER_SPORTS_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 25,
  },
  60: {
    strength: 3,
    endurance: 6,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -4,
    thirst: -4,
    sleepiness: -4,
    energy: -7,
    health: 4,
    xp: 50,
  },
  90: {
    strength: 4,
    endurance: 9,
    flexibility: 3,
    agility: 4,
    speed: 3,
    reflex: 4,
    hunger: -6,
    thirst: -7,
    sleepiness: -6,
    energy: -12,
    health: 5,
    xp: 75,
  },
};

// Катание на коньках
export const ICE_SKATING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 30,
  },
  40: {
    strength: 3,
    endurance: 6,
    flexibility: 2,
    agility: 5,
    speed: 4,
    reflex: 5,
    hunger: -4,
    thirst: -4,
    sleepiness: -4,
    energy: -7,
    health: 4,
    xp: 60,
  },
  60: {
    strength: 4,
    endurance: 9,
    flexibility: 3,
    agility: 7,
    speed: 6,
    reflex: 7,
    hunger: -6,
    thirst: -7,
    sleepiness: -6,
    energy: -12,
    health: 5,
    xp: 90,
  },
};

// Хоккей (улица / зал)
export const HOCKEY_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -2,
    thirst: -3,
    sleepiness: -2,
    energy: -5,
    health: 1,
    xp: 40,
  },
  40: {
    strength: 4,
    endurance: 6,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 7,
    hunger: -5,
    thirst: -6,
    sleepiness: -4,
    energy: -11,
    health: 3,
    xp: 80,
  },
  60: {
    strength: 6,
    endurance: 9,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 10,
    hunger: -8,
    thirst: -10,
    sleepiness: -6,
    energy: -18,
    health: 4,
    xp: 110,
  },
};

// Кёрлинг
export const CURLING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 1,
    endurance: 1,
    flexibility: 0,
    agility: 2,
    speed: 0,
    reflex: 1,
    hunger: 0,
    thirst: 0,
    sleepiness: -1,
    energy: -1,
    health: 1,
    xp: 15,
  },
  60: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 3,
    xp: 30,
  },
  90: {
    strength: 3,
    endurance: 4,
    flexibility: 1,
    agility: 4,
    speed: 1,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -4,
    health: 4,
    xp: 45,
  },
};

// Бокс
export const BOXING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -5,
    health: 0,
    xp: 35,
  },
  40: {
    strength: 6,
    endurance: 6,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 7,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -11,
    health: -2,
    xp: 70,
  },
  60: {
    strength: 9,
    endurance: 9,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 10,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -18,
    health: -5,
    xp: 100,
  },
};

// Кикбоксинг
export const KICKBOXING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 4,
    flexibility: 2,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -2,
    thirst: -3,
    sleepiness: -2,
    energy: -5,
    health: 0,
    xp: 40,
  },
  40: {
    strength: 5,
    endurance: 7,
    flexibility: 3,
    agility: 5,
    speed: 5,
    reflex: 7,
    hunger: -5,
    thirst: -6,
    sleepiness: -4,
    energy: -11,
    health: -2,
    xp: 80,
  },
  60: {
    strength: 7,
    endurance: 10,
    flexibility: 4,
    agility: 7,
    speed: 7,
    reflex: 10,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -18,
    health: -5,
    xp: 110,
  },
};

// Боевые искусства (общее)
export const MARTIAL_ARTS_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 2,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 1,
    xp: 30,
  },
  40: {
    strength: 4,
    endurance: 4,
    flexibility: 4,
    agility: 5,
    speed: 4,
    reflex: 6,
    hunger: -3,
    thirst: -3,
    sleepiness: -4,
    energy: -7,
    health: 2,
    xp: 60,
  },
  60: {
    strength: 6,
    endurance: 6,
    flexibility: 5,
    agility: 7,
    speed: 6,
    reflex: 8,
    hunger: -5,
    thirst: -5,
    sleepiness: -6,
    energy: -12,
    health: 3,
    xp: 90,
  },
};

// Борьба
export const WRESTLING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 4,
    endurance: 2,
    flexibility: 2,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -3,
    thirst: -2,
    sleepiness: -1,
    energy: -6,
    health: -1,
    xp: 35,
  },
  40: {
    strength: 8,
    endurance: 5,
    flexibility: 4,
    agility: 4,
    speed: 2,
    reflex: 4,
    hunger: -6,
    thirst: -5,
    sleepiness: -3,
    energy: -13,
    health: -4,
    xp: 70,
  },
  60: {
    strength: 12,
    endurance: 8,
    flexibility: 6,
    agility: 6,
    speed: 3,
    reflex: 6,
    hunger: -10,
    thirst: -8,
    sleepiness: -5,
    energy: -22,
    health: -8,
    xp: 105,
  },
};

// Тайцзи (Тайцзицюань)
export const TAI_CHI_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 1,
    flexibility: 3,
    agility: 2,
    speed: 0,
    reflex: 1,
    hunger: 0,
    thirst: 0,
    sleepiness: -4,
    energy: -1,
    health: 3,
    xp: 15,
  },
  40: {
    strength: 2,
    endurance: 2,
    flexibility: 6,
    agility: 4,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -7,
    energy: -2,
    health: 6,
    xp: 30,
  },
  60: {
    strength: 3,
    endurance: 3,
    flexibility: 8,
    agility: 5,
    speed: 1,
    reflex: 3,
    hunger: -1,
    thirst: -1,
    sleepiness: -10,
    energy: -3,
    health: 8,
    xp: 45,
  },
};

// Танцы (общее, зумба и т.д.)
export const DANCING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 3,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 25,
  },
  40: {
    strength: 2,
    endurance: 6,
    flexibility: 4,
    agility: 5,
    speed: 4,
    reflex: 4,
    hunger: -3,
    thirst: -3,
    sleepiness: -4,
    energy: -7,
    health: 4,
    xp: 50,
  },
  60: {
    strength: 3,
    endurance: 9,
    flexibility: 6,
    agility: 7,
    speed: 6,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -6,
    energy: -12,
    health: 5,
    xp: 75,
  },
};

// Социальные танцы (парные)
export const SOCIAL_DANCING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 2,
    flexibility: 3,
    agility: 3,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -3,
    energy: -2,
    health: 2,
    xp: 20,
  },
  40: {
    strength: 2,
    endurance: 4,
    flexibility: 5,
    agility: 5,
    speed: 2,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -5,
    energy: -4,
    health: 4,
    xp: 40,
  },
  60: {
    strength: 3,
    endurance: 6,
    flexibility: 7,
    agility: 7,
    speed: 3,
    reflex: 4,
    hunger: -3,
    thirst: -3,
    sleepiness: -7,
    energy: -6,
    health: 6,
    xp: 60,
  },
};

// Мультиспорт (триатлон: плавание → велосипед → бег)
export const MULTISPORT_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 5,
    flexibility: 1,
    agility: 2,
    speed: 2,
    reflex: 2,
    hunger: -3,
    thirst: -3,
    sleepiness: -3,
    energy: -6,
    health: 1,
    xp: 45,
  },
  60: {
    strength: 4,
    endurance: 10,
    flexibility: 2,
    agility: 4,
    speed: 4,
    reflex: 4,
    hunger: -7,
    thirst: -7,
    sleepiness: -6,
    energy: -14,
    health: 3,
    xp: 90,
  },
  90: {
    strength: 6,
    endurance: 15,
    flexibility: 3,
    agility: 6,
    speed: 6,
    reflex: 6,
    hunger: -11,
    thirst: -11,
    sleepiness: -8,
    energy: -22,
    health: 4,
    xp: 130,
  },
};

// Гольф
export const GOLF_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 1,
    endurance: 1,
    flexibility: 1,
    agility: 2,
    speed: 0,
    reflex: 2,
    hunger: 0,
    thirst: 0,
    sleepiness: -1,
    energy: -1,
    health: 1,
    xp: 15,
  },
  60: {
    strength: 2,
    endurance: 2,
    flexibility: 2,
    agility: 3,
    speed: 1,
    reflex: 3,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -2,
    health: 2,
    xp: 30,
  },
  90: {
    strength: 3,
    endurance: 3,
    flexibility: 3,
    agility: 4,
    speed: 1,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -3,
    health: 3,
    xp: 45,
  },
};

// Боулинг
export const BOWLING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 0,
    flexibility: 0,
    agility: 1,
    speed: 0,
    reflex: 1,
    hunger: 0,
    thirst: 0,
    sleepiness: 0,
    energy: -1,
    health: 1,
    xp: 10,
  },
  40: {
    strength: 2,
    endurance: 1,
    flexibility: 1,
    agility: 2,
    speed: 0,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 2,
    xp: 20,
  },
  60: {
    strength: 3,
    endurance: 2,
    flexibility: 1,
    agility: 3,
    speed: 1,
    reflex: 3,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 3,
    xp: 30,
  },
};

// Стрельба из лука
export const ARCHERY_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 0,
    flexibility: 1,
    agility: 2,
    speed: 0,
    reflex: 3,
    hunger: 0,
    thirst: 0,
    sleepiness: -1,
    energy: -1,
    health: 1,
    xp: 15,
  },
  40: {
    strength: 3,
    endurance: 1,
    flexibility: 2,
    agility: 4,
    speed: 0,
    reflex: 5,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -2,
    health: 2,
    xp: 30,
  },
  60: {
    strength: 4,
    endurance: 2,
    flexibility: 3,
    agility: 5,
    speed: 0,
    reflex: 7,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -3,
    health: 3,
    xp: 45,
  },
};

// Верховая езда
export const HORSEBACK_RIDING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 2,
    flexibility: 2,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -2,
    health: 2,
    xp: 25,
  },
  40: {
    strength: 4,
    endurance: 4,
    flexibility: 4,
    agility: 4,
    speed: 2,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -4,
    energy: -4,
    health: 4,
    xp: 50,
  },
  60: {
    strength: 6,
    endurance: 6,
    flexibility: 5,
    agility: 6,
    speed: 3,
    reflex: 6,
    hunger: -3,
    thirst: -3,
    sleepiness: -6,
    energy: -6,
    health: 5,
    xp: 75,
  },
};

// Рыбалка
export const FISHING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 0,
    endurance: 1,
    flexibility: 0,
    agility: 1,
    speed: 0,
    reflex: 1,
    hunger: 0,
    thirst: 0,
    sleepiness: -1,
    energy: -1,
    health: 2,
    xp: 10,
  },
  60: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 2,
    speed: 0,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -2,
    health: 3,
    xp: 20,
  },
  90: {
    strength: 1,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 0,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -3,
    health: 4,
    xp: 30,
  },
};

// Охота
export const HUNTING_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -2,
    health: 2,
    xp: 20,
  },
  60: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 4,
    speed: 2,
    reflex: 4,
    hunger: -2,
    thirst: -3,
    sleepiness: -4,
    energy: -4,
    health: 4,
    xp: 40,
  },
  90: {
    strength: 3,
    endurance: 6,
    flexibility: 3,
    agility: 6,
    speed: 3,
    reflex: 6,
    hunger: -3,
    thirst: -5,
    sleepiness: -6,
    energy: -6,
    health: 5,
    xp: 60,
  },
};

// Фитнес-игры (VR / активные видеоигры)
export const FITNESS_GAMES_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 2,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 1,
    xp: 15,
  },
  30: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 3,
    speed: 2,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 2,
    xp: 30,
  },
  45: {
    strength: 3,
    endurance: 6,
    flexibility: 3,
    agility: 4,
    speed: 3,
    reflex: 6,
    hunger: -3,
    thirst: -3,
    sleepiness: -3,
    energy: -6,
    health: 3,
    xp: 45,
  },
};

// Игры (активные игры на площадке)
export const ACTIVE_GAMES_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 2,
    speed: 2,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 1,
    xp: 20,
  },
  30: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 4,
    speed: 4,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -5,
    health: 3,
    xp: 40,
  },
  45: {
    strength: 3,
    endurance: 6,
    flexibility: 3,
    agility: 6,
    speed: 6,
    reflex: 6,
    hunger: -4,
    thirst: -4,
    sleepiness: -3,
    energy: -8,
    health: 4,
    xp: 60,
  },
};

// Скалолазание
export const ROCK_CLIMBING_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 3,
    endurance: 2,
    flexibility: 3,
    agility: 3,
    speed: 1,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 1,
    xp: 35,
  },
  40: {
    strength: 6,
    endurance: 4,
    flexibility: 6,
    agility: 5,
    speed: 2,
    reflex: 4,
    hunger: -4,
    thirst: -4,
    sleepiness: -4,
    energy: -9,
    health: 3,
    xp: 70,
  },
  60: {
    strength: 9,
    endurance: 6,
    flexibility: 8,
    agility: 7,
    speed: 3,
    reflex: 6,
    hunger: -7,
    thirst: -7,
    sleepiness: -6,
    energy: -15,
    health: 4,
    xp: 100,
  },
};

// Гимнастика
export const GYMNASTICS_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 2,
    flexibility: 4,
    agility: 4,
    speed: 1,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -3,
    energy: -3,
    health: 2,
    xp: 30,
  },
  40: {
    strength: 4,
    endurance: 4,
    flexibility: 8,
    agility: 7,
    speed: 2,
    reflex: 4,
    hunger: -3,
    thirst: -3,
    sleepiness: -5,
    energy: -6,
    health: 4,
    xp: 60,
  },
  60: {
    strength: 6,
    endurance: 6,
    flexibility: 12,
    agility: 10,
    speed: 3,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -7,
    energy: -9,
    health: 5,
    xp: 90,
  },
};

// Кресло-коляска (темп ходьбы / бега)
export const WHEELCHAIR_EFFECTS: WorkoutEffectTable = {
  15: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 1,
    speed: 2,
    reflex: 1,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 20,
  },
  30: {
    strength: 4,
    endurance: 6,
    flexibility: 2,
    agility: 2,
    speed: 4,
    reflex: 2,
    hunger: -2,
    thirst: -2,
    sleepiness: -4,
    energy: -6,
    health: 4,
    xp: 40,
  },
  45: {
    strength: 6,
    endurance: 9,
    flexibility: 3,
    agility: 3,
    speed: 6,
    reflex: 3,
    hunger: -4,
    thirst: -4,
    sleepiness: -6,
    energy: -9,
    health: 6,
    xp: 60,
  },
};

// Футбол (классический / американский / австралийский)
export const FOOTBALL_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 4,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -2,
    thirst: -3,
    sleepiness: -2,
    energy: -5,
    health: 1,
    xp: 40,
  },
  60: {
    strength: 4,
    endurance: 8,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 5,
    hunger: -5,
    thirst: -6,
    sleepiness: -4,
    energy: -11,
    health: 3,
    xp: 80,
  },
  90: {
    strength: 6,
    endurance: 12,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 7,
    hunger: -8,
    thirst: -10,
    sleepiness: -6,
    energy: -18,
    health: 4,
    xp: 110,
  },
};

// Баскетбол
export const BASKETBALL_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 2,
    xp: 35,
  },
  60: {
    strength: 4,
    endurance: 6,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 70,
  },
  90: {
    strength: 5,
    endurance: 9,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 8,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 5,
    xp: 100,
  },
};

// Волейбол
export const VOLLEYBALL_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 2,
    flexibility: 1,
    agility: 3,
    speed: 2,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 30,
  },
  60: {
    strength: 3,
    endurance: 4,
    flexibility: 2,
    agility: 5,
    speed: 3,
    reflex: 5,
    hunger: -4,
    thirst: -4,
    sleepiness: -4,
    energy: -7,
    health: 4,
    xp: 60,
  },
  90: {
    strength: 4,
    endurance: 6,
    flexibility: 3,
    agility: 7,
    speed: 4,
    reflex: 7,
    hunger: -6,
    thirst: -7,
    sleepiness: -6,
    energy: -12,
    health: 5,
    xp: 90,
  },
};

// Теннис
export const TENNIS_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 2,
    xp: 35,
  },
  60: {
    strength: 3,
    endurance: 5,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 7,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 70,
  },
  90: {
    strength: 4,
    endurance: 7,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 9,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 5,
    xp: 100,
  },
};

// Настольный теннис
export const TABLE_TENNIS_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 0,
    endurance: 1,
    flexibility: 0,
    agility: 2,
    speed: 2,
    reflex: 3,
    hunger: 0,
    thirst: 0,
    sleepiness: -1,
    energy: -1,
    health: 1,
    xp: 15,
  },
  40: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 5,
    hunger: -1,
    thirst: -1,
    sleepiness: -2,
    energy: -3,
    health: 2,
    xp: 30,
  },
  60: {
    strength: 1,
    endurance: 3,
    flexibility: 1,
    agility: 4,
    speed: 4,
    reflex: 7,
    hunger: -2,
    thirst: -2,
    sleepiness: -3,
    energy: -5,
    health: 3,
    xp: 45,
  },
};

// Бадминтон
export const BADMINTON_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 1,
    xp: 25,
  },
  40: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 5,
    hunger: -3,
    thirst: -3,
    sleepiness: -3,
    energy: -5,
    health: 3,
    xp: 50,
  },
  60: {
    strength: 3,
    endurance: 6,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 7,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 75,
  },
};

// Сквош / Ракетбол
export const SQUASH_RACQUETBALL_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -3,
    health: 1,
    xp: 30,
  },
  40: {
    strength: 3,
    endurance: 5,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 7,
    hunger: -4,
    thirst: -4,
    sleepiness: -4,
    energy: -7,
    health: 3,
    xp: 60,
  },
  60: {
    strength: 4,
    endurance: 7,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 9,
    hunger: -6,
    thirst: -7,
    sleepiness: -6,
    energy: -12,
    health: 4,
    xp: 90,
  },
};

// Бейсбол / Софтбол / Крикет
export const BASEBALL_SOFTBALL_CRICKET_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 2,
    flexibility: 1,
    agility: 2,
    speed: 2,
    reflex: 3,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 1,
    xp: 20,
  },
  60: {
    strength: 3,
    endurance: 4,
    flexibility: 2,
    agility: 3,
    speed: 3,
    reflex: 4,
    hunger: -3,
    thirst: -3,
    sleepiness: -2,
    energy: -4,
    health: 3,
    xp: 40,
  },
  90: {
    strength: 4,
    endurance: 5,
    flexibility: 2,
    agility: 4,
    speed: 4,
    reflex: 5,
    hunger: -4,
    thirst: -4,
    sleepiness: -3,
    energy: -6,
    health: 4,
    xp: 60,
  },
};

// Регби
export const RUGBY_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 3,
    endurance: 4,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -2,
    thirst: -3,
    sleepiness: -2,
    energy: -6,
    health: 0,
    xp: 45,
  },
  60: {
    strength: 6,
    endurance: 8,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 6,
    hunger: -6,
    thirst: -7,
    sleepiness: -4,
    energy: -12,
    health: 2,
    xp: 90,
  },
  90: {
    strength: 8,
    endurance: 12,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 8,
    hunger: -9,
    thirst: -11,
    sleepiness: -6,
    energy: -20,
    health: 2,
    xp: 120,
  },
};

// Гандбол
export const HANDBALL_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 1,
    xp: 35,
  },
  60: {
    strength: 3,
    endurance: 6,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 3,
    xp: 70,
  },
  90: {
    strength: 4,
    endurance: 9,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 8,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 4,
    xp: 100,
  },
};

// Лакросс
export const LACROSSE_EFFECTS: WorkoutEffectTable = {
  30: {
    strength: 2,
    endurance: 3,
    flexibility: 1,
    agility: 3,
    speed: 3,
    reflex: 3,
    hunger: -2,
    thirst: -2,
    sleepiness: -2,
    energy: -4,
    health: 1,
    xp: 40,
  },
  60: {
    strength: 4,
    endurance: 6,
    flexibility: 2,
    agility: 5,
    speed: 5,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 3,
    xp: 80,
  },
  90: {
    strength: 6,
    endurance: 9,
    flexibility: 3,
    agility: 7,
    speed: 7,
    reflex: 8,
    hunger: -8,
    thirst: -9,
    sleepiness: -6,
    energy: -15,
    health: 4,
    xp: 110,
  },
};

// Фрисби (диск-гольф / алтимат)
export const FRISBEE_EFFECTS: WorkoutEffectTable = {
  20: {
    strength: 1,
    endurance: 2,
    flexibility: 1,
    agility: 3,
    speed: 2,
    reflex: 2,
    hunger: -1,
    thirst: -1,
    sleepiness: -1,
    energy: -2,
    health: 1,
    xp: 25,
  },
  40: {
    strength: 2,
    endurance: 4,
    flexibility: 2,
    agility: 5,
    speed: 4,
    reflex: 4,
    hunger: -3,
    thirst: -3,
    sleepiness: -3,
    energy: -5,
    health: 3,
    xp: 50,
  },
  60: {
    strength: 3,
    endurance: 6,
    flexibility: 3,
    agility: 7,
    speed: 6,
    reflex: 6,
    hunger: -5,
    thirst: -5,
    sleepiness: -4,
    energy: -9,
    health: 4,
    xp: 75,
  },
};

// Маппинг типов тренировок на их эффекты
export const WORKOUT_EFFECTS_MAP: Record<string, WorkoutEffectTable> = {
  'Ходьба (на улице / в зале)': WALKING_EFFECTS,
  'Бег (на улице / в зале / на беговой дорожке)': RUNNING_EFFECTS,
  'Велосипед (на улице / в зале)': CYCLING_EFFECTS,
  'Эллипсоид': ELLIPTICAL_EFFECTS,
  'Эргометр (Гребля в зале)': ROWING_EFFECTS,
  'Степпер (Лестница)': STEPPER_EFFECTS,
  'Хайкинг (Пеший туризм)': HIKING_EFFECTS,
  'ВИИТ (Высокоинтенсивная интервальная тренировка / HIIT)': HIIT_EFFECTS,
  'Скакалка': JUMP_ROPE_EFFECTS,
  'Традиционная силовая тренировка (с весами/тренажерами)': STRENGTH_TRAINING_EFFECTS,
  'Функционально-силовая тренировка (с собственным весом, кроссфит)': FUNCTIONAL_STRENGTH_EFFECTS,
  'Кор (Тренировка мышц кора/пресса)': CORE_EFFECTS,
  'Пилатес': PILATES_EFFECTS,
  'Йога': YOGA_EFFECTS,
  'Барре (Балетная тренировка)': BARRE_EFFECTS,
  'Растяжка (Flexibility)': STRETCHING_EFFECTS,
  'Заминка (Восстановление после тренировки)': COOLDOWN_EFFECTS,
  'Смешанная кардио': MIXED_CARDIO_EFFECTS,
  'Плавание в бассейне (считает круги)': POOL_SWIMMING_EFFECTS,
  'Плавание в открытой воде (использует GPS)': OPEN_WATER_SWIMMING_EFFECTS,
  'Водные виды спорта (общее)': WATER_SPORTS_EFFECTS,
  'Аквааэробика (Фитнес на воді)': AQUA_AEROBICS_EFFECTS,
  'Сёрфинг': SURFING_EFFECTS,
  'Парусный спорт': SAILING_EFFECTS,
  'Гребля (на улице)': OUTDOOR_ROWING_EFFECTS,
  'Паддл-спорт (Гребля на байдарках/каноэ)': PADDLE_SPORTS_EFFECTS,
  'Водное поло': WATER_POLO_EFFECTS,
  'Лыжи (Бег на лыжах / Спуск со склона)': SKIING_EFFECTS,
  'Сноубординг': SNOWBOARDING_EFFECTS,
  'Зимние виды спорта (общее)': WINTER_SPORTS_EFFECTS,
  'Катание на коньках': ICE_SKATING_EFFECTS,
  'Хоккей (на улице / в зале)': HOCKEY_EFFECTS,
  'Кёрлинг': CURLING_EFFECTS,
  'Бокс': BOXING_EFFECTS,
  'Кикбоксинг': KICKBOXING_EFFECTS,
  'Боевые искусства (общее)': MARTIAL_ARTS_EFFECTS,
  'Борьба': WRESTLING_EFFECTS,
  'Тайцзи (Тайцзицюань)': TAI_CHI_EFFECTS,
  'Танцы (общее, подходит для зумбы и т.д.)': DANCING_EFFECTS,
  'Социальные танцы (парные)': SOCIAL_DANCING_EFFECTS,
  'Мультиспорт (Автоматическое переключение, например, для триатлона: Плаваение → Велосипед → Бег).': MULTISPORT_EFFECTS,
  'Гольф': GOLF_EFFECTS,
  'Боулинг': BOWLING_EFFECTS,
  'Стрельба из лука': ARCHERY_EFFECTS,
  'Верховая езда': HORSEBACK_RIDING_EFFECTS,
  'Рыбалка': FISHING_EFFECTS,
  'Охота': HUNTING_EFFECTS,
  'Фитнес-игры (для VR или активных видеоигр)': FITNESS_GAMES_EFFECTS,
  'Игры (активные игры на площадке)': ACTIVE_GAMES_EFFECTS,
  'Скалолазание': ROCK_CLIMBING_EFFECTS,
  'Гимнастика': GYMNASTICS_EFFECTS,
  'Кресло-коляска (В темпе ходьбы / В темпе бега)': WHEELCHAIR_EFFECTS,
  'Футбол (Классический / Американский / Австралийский)': FOOTBALL_EFFECTS,
  'Баскетбол': BASKETBALL_EFFECTS,
  'Волейбол': VOLLEYBALL_EFFECTS,
  'Теннис': TENNIS_EFFECTS,
  'Настольный теннис': TABLE_TENNIS_EFFECTS,
  'Бадминтон': BADMINTON_EFFECTS,
  'Сквош / Ракетбол': SQUASH_RACQUETBALL_EFFECTS,
  'Бейсбол / Софтбол / Крикет': BASEBALL_SOFTBALL_CRICKET_EFFECTS,
  'Регби': RUGBY_EFFECTS,
  'Гандбол': HANDBALL_EFFECTS,
  'Лакросс': LACROSSE_EFFECTS,
  'Фрисби (Диск-гольф / Алтимат)': FRISBEE_EFFECTS,
};

